### ISSUE TITLE
Toppings 스크롤 추가

### ISSUE THREAD

**Issue by kyusooK** [msa-ez/platform#15]
![image](https://github.com/msa-ez/platform/assets/123912988/564464b0-b745-4561-bd31-ec248c343da3)

Custom Topping으로 여러개를 적용했을 경우 해당 화면의 스크롤이 적용되지 않아 적용한 토핑이 일부 노출이 되지않고있음.

**Comment by kibum0405** [comment]
![image](https://github.com/msa-ez/platform/assets/59447401/15b6e354-ecc4-46fd-8884-b5361440c542)
