### ISSUE TITLE
강의화면 상단 검정색 막대바 제거

### ISSUE THREAD

**Issue by kyusooK** [msa-ez/platform#21]
![image](https://github.com/msa-ez/platform/assets/123912988/e8ca3fb5-6188-4a5f-b2f8-9048d58d05cd)<br>

랩 진입시 상단에 나타나는 검정 막대바 제거

**Comment by kibum0405** [comment]
![Uploading 스크린샷 2024-06-24 오후 1.42.00.png…]()
