### ISSUE TITLE
Examples) Command Default verb 비활성화

### ISSUE THREAD

**Issue by kyusooK** [msa-ez/platform#55]
<img width="1343" alt="image" src="https://github.com/user-attachments/assets/bbd0803c-aec6-4e41-891e-65c7d1a7d36c">
<img width="495" alt="image" src="https://github.com/user-attachments/assets/6ab98da4-fed8-4e5b-8885-86de99443c4a">

Default Verb일때는 parameter값이 존재하지 않아 when field의 값이 없기에 examples의 사용이 되지 않아 비활성화 필요

**Comment by jinyoung** [comment]
그때는 비활성화 하는게 아니라 post 인 경우는   aggregate field 들이 when 의 입력 필드들이되어야 합니다.
Delete 인 경우는 id 값이 되고.

2024년 10월 17일 (목) 오전 11:17, KimKyusoo ***@***.***>님이 작성:

**Comment by jinyoung** [comment]
그리고 다른 이야긴데, "Describe your business logic" 부분이 타이틀 처럼 보이니, 뒤에 "here"를 붙여서 "Describe your business logic here" 로 변경바랍니다~
